[package]
name = "satchel"
version = "0.1.0"
description = "Satchel - Your Academic Workbench"
authors = []
license = ""
repository = ""
default-run = "satchel"
edition = "2021"
rust-version = "1.60"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
tauri = { version = "1.6", features = ["shell-open", "dialog-open", "fs-copy-file", "fs-create-dir", "fs-exists", "fs-remove-file", "path-all"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[features]
custom-protocol = ["tauri/custom-protocol"]
